improve user experience with subcommands and flags

diff --git a/webapp b/webapp
--- a/webapp
+++ b/webapp
@@ -1,45 +1,128 @@
 #!/bin/bash
 
 FIREFOX_CONFIG_DIR=$HOME/.mozilla/firefox
+INSTALLED_FILENAME=installed.txt
 
-# check if similarly named webapp was already created
-if [ $(find $HOME/.mozilla/firefox -name "*$2"  | wc -l) -gt 0 ];
-then
-    echo "A similarly named webapp was already created!"
+__check_similar_name_installed(){
+    if [ $(find $HOME/.mozilla/firefox -name "*$1"  | wc -l) -gt 0 ];
+    then
+        echo "A similarly named webapp was already created!"
+        exit 1
+    fi
+}
+
+
+
+__install_privacy_addons(){
+    mkdir $PROFILE_DIR/extensions
+    # ublock origin
+    wget "https://addons.mozilla.org/firefox/downloads/file/3853583/ublock_origin-1.38.6-an+fx.xpi" -O $1/extensions/uBlock0@raymondhill.net.xpi
+    # decentraleyes
+    wget "https://addons.mozilla.org/firefox/downloads/file/3833987/decentraleyes-2.0.16-an+fx.xpi" -O $1/extensions/jid1-BoFifL9Vbdl2zQ@jetpack.xpi
+}
+
+findicon(){
+    query=$1
+    while getopts ":i" opt; do
+        case $opt in
+            i)
+                query="$OPTARG"
+                ;;
+            \?)
+                echo "Invalid option: -$OPTARG" >&2
+                ;;
+        esac
+    done
+
+    if [ $(find /usr/share/icons -name "*$query*"  | wc -l) -gt 0 ];
+    then
+        find /usr/share/icons -name "*$query*" | while read line; do
+            echo $line | awk -F / '{print $5 ": " $8}' | rev | cut -c 5- | rev
+        done
+    else
+        echo "No icons found!"
+        echo "Install the Papirus icon theme to get more variety :)"
+    fi
+}
+
+install(){
+    link=$1
+    name=$2
+    icon="applications-webapps"
+    privacy=false
+    while getopts ":l:n:i:p" opt; do
+        case $opt in
+            l)
+                link="$OPTARG"
+                ;;
+            n)
+                name="$OPTARG"
+                ;;
+            i)
+                icon="$OPTARG"
+                ;;
+            p)
+                privacy=true
+                ;;
+            :)
+                echo "Option -$OPTARG requires an argument." >&2
+                exit 1
+                ;;
+            \?)
+                echo "Invalid option: -$OPTARG" >&2
+                exit 1
+                ;;
+        esac
+    done
+    __check_similar_name_installed $name
+
+    # create a new Firefox profile with a unique name
+    PROFILE_NAME="$(uuidgen)-$name"
+    firefox -CreateProfile $PROFILE_NAME
+
+    # write profile name to a file, to facilitate uninstallation
+    if [ -f ./$INSTALLED_FILENAME]; then
+        echo $PROFILE_NAME >> ./$INSTALLED_FILENAME
+    else
+        touch ./installed.txt
+        echo $PROFILE_NAME >> ./$INSTALLED_FILENAME
+    fi
+
+    # get absolute path to newly created profile
+    PROFILE_DIR=$(find $FIREFOX_CONFIG_DIR -name "*$PROFILE_NAME")
+
+    # copy user.js file to profile directory
+    cp "./user.js" "$PROFILE_DIR"
+
+    # copy userChrome.css to profile directory
+    mkdir $PROFILE_DIR/chrome
+    cp ./userChrome.css $PROFILE_DIR/chrome/
+
+    # install privacy addons if asked to do that
+    if [ "$privacy" = true ]; then
+        __install_privacy_addons $PROFILE_DIR
+    fi
+
+    # write a desktop entry
+    CONTENT=$(cat <<EOF
+    [Desktop Entry]\n
+    Version=1.0\n
+    Type=Application\n
+    Name=$2\n
+    Icon=$icon\n
+    Exec=firefox --no-remote -P "$PROFILE_NAME" --name=$2 --class=$2 $1\n
+    Categories=Utility;\n
+    StartupWMClass=$2\n
+    EOF
+    )
+
+    echo -e $CONTENT > $HOME/.local/share/applications/$PROFILE_NAME-webapp.desktop
+
+}
+
+if [[ $1 =~ ^(install|remove|uninstall|findicon)$ ]]; then
+    "$@"
+else
+    echo "Invalid subcommand $1" >&2
     exit 1
 fi
-
-# create a new Firefox profile with a unique name
-PROFILE_NAME="$(uuidgen)-$2"
-firefox -CreateProfile $PROFILE_NAME
-
-# get absolute path to newly created profile
-PROFILE_DIR=$(find $FIREFOX_CONFIG_DIR -name "*$PROFILE_NAME")
-
-# copy user.js file
-cp "./user.js" "$PROFILE_DIR"
-
-# copy userChrome.css
-mkdir $PROFILE_DIR/chrome
-cp ./userChrome.css $PROFILE_DIR/chrome/
-
-# install ublock origin
-mkdir $PROFILE_DIR/extensions
-wget "https://addons.mozilla.org/firefox/downloads/file/3853583/ublock_origin-1.38.6-an+fx.xpi" -O $PROFILE_DIR/extensions/uBlock0@raymondhill.net.xpi
-wget "https://addons.mozilla.org/firefox/downloads/file/3833987/decentraleyes-2.0.16-an+fx.xpi" -O $PROFILE_DIR/extensions/jid1-BoFifL9Vbdl2zQ@jetpack.xpi
-
-# write a desktop entry
-CONTENT=$(cat <<EOF
-[Desktop Entry]\n
-Version=1.0\n
-Type=Application\n
-Name=$2\n
-Icon=applications-webapps\n
-Exec=firefox --no-remote -P "$PROFILE_NAME" --name=$2 --class=$2 $1\n
-Categories=Utility;\n
-StartupWMClass=$2\n
-EOF
-)
-
-LOWERCASE_APP_NAME=$(echo "$2" | tr '[:upper:]' '[:lower:]')
-echo -e $CONTENT > $HOME/.local/share/applications/$LOWERCASE_APP_NAME-webapp.desktop
